<?php

namespace App\Support;

use Illuminate\Http\Response;

class LiveStyleSitemap
{
    private const SITE_URL = 'https://buderus-gasthermenwartung.at';
    private const STYLESHEET_URL = '//buderus-gasthermenwartung.at/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl';
    private const PAGE_LASTMOD = '2026-04-17T15:28:46+00:00';
    private const ELEMENTOR_LASTMOD = '2026-02-03T14:05:16+00:00';

    public static function indexResponse(): Response
    {
        $xml = self::indexXml();

        return response($xml, 200, ['Content-Type' => 'application/xml; charset=UTF-8']);
    }

    public static function legacyIndexResponse(): Response
    {
        return response(self::indexXml(), 301, [
            'Content-Type' => 'application/xml; charset=UTF-8',
            'Location' => url('/sitemap_index.xml'),
        ]);
    }

    public static function pageResponse(): Response
    {
        $xml = self::xmlDeclaration()
            . self::stylesheetDeclaration()
            . '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            . self::urlNode(self::SITE_URL . '/', self::PAGE_LASTMOD)
            . self::urlNode(self::SITE_URL . '/datenschutz/', self::PAGE_LASTMOD)
            . '</urlset>'
            . self::generatorComment();

        return response($xml, 200, ['Content-Type' => 'application/xml; charset=UTF-8']);
    }

    public static function elementorResponse(): Response
    {
        $xml = self::xmlDeclaration()
            . self::stylesheetDeclaration()
            . '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            . self::urlNode(self::SITE_URL . '/elementor-hf/19/', self::ELEMENTOR_LASTMOD)
            . self::urlNode(self::SITE_URL . '/elementor-hf/footer/', self::ELEMENTOR_LASTMOD)
            . '</urlset>'
            . self::generatorComment();

        return response($xml, 200, ['Content-Type' => 'application/xml; charset=UTF-8']);
    }

    private static function sitemapNode(string $loc, string $lastmod): string
    {
        return '<sitemap><loc>' . self::escape($loc) . '</loc><lastmod>' . self::escape($lastmod) . '</lastmod></sitemap>';
    }

    private static function urlNode(string $loc, string $lastmod): string
    {
        return '<url><loc>' . self::escape($loc) . '</loc><lastmod>' . self::escape($lastmod) . '</lastmod></url>';
    }

    private static function xmlDeclaration(): string
    {
        return '<?xml version="1.0" encoding="UTF-8"?>';
    }

    private static function indexXml(): string
    {
        return self::xmlDeclaration()
            . self::stylesheetDeclaration()
            . '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            . self::sitemapNode(self::SITE_URL . '/page-sitemap.xml', self::PAGE_LASTMOD)
            . self::sitemapNode(self::SITE_URL . '/elementor-hf-sitemap.xml', self::ELEMENTOR_LASTMOD)
            . '</sitemapindex>'
            . self::generatorComment();
    }

    private static function stylesheetDeclaration(): string
    {
        return '<?xml-stylesheet type="text/xsl" href="' . self::STYLESHEET_URL . '"?>';
    }

    private static function generatorComment(): string
    {
        return '<!-- XML Sitemap generated by Yoast SEO -->';
    }

    private static function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_XML1);
    }
}
